#!/usr/bin/env python3
import os
import sys
import socket



def main():
    if len(sys.argv) < 2:
        print('Usage: automations <command>')
        return
        
    SOCKET_PATH = os.environ.get('AUTOMATIONS_SOCKET_PATH', None)
    if SOCKET_PATH is None:
        print("AUTOMATIONS_SOCKET_PATH environment variable was not set by systemd.service, did you forget to call 'source ~/.bashrc' after './setup.sh' ?")   
        return

    cmd = ' '.join(sys.argv[1:])
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as client:
        client.connect(SOCKET_PATH)
        client.sendall(cmd.encode())
        response = client.recv(4096).decode()
        print(response, end='')

if __name__ == '__main__':
    main()
